# **Task : Build a Single-Layer Neural Network**
### Create a single-layer neural network with 4 neurons.

### Use random weights and biases for the layer.
### Apply the **ReLU** activation function to the output of the layer.
### Test the network with the following input:

# **inputs = np.array([0.2, 0.4, 0.6, 0.8])**
Print the output of the layer before and after applying the activation function.



# **Answer 1**

In [1]:
data = {
    'Product' :['laptop','phone','headphone'],
    'Price' : [120000,15000, 1500],
    'Quantity' : [10,50,100]
}

In [2]:
import pandas as pd
df = pd.DataFrame(data)

In [3]:
df

Product   Price  Quantity
0     laptop  120000        10
1      phone   15000        50
2  headphone    1500       100

In [4]:
df['Total'] = df['Price']*df['Quantity']

In [5]:
df

Product   Price  Quantity    Total
0     laptop  120000        10  1200000
1      phone   15000        50   750000
2  headphone    1500       100   150000

In [6]:
import numpy as np
input = np.array([0.2,0.4,0.6,0.8])

In [10]:
from random import random
weight = np.ones((4, 4))
weight *= np.random.rand(4, 4)
print(weight)

[[0.29632602 0.3183446  0.76131734 0.23734957]
 [0.17799081 0.81484944 0.14384794 0.56015501]
 [0.99553363 0.5413439  0.1619462  0.49036551]
 [0.46695947 0.02080508 0.59760795 0.42690536]]


In [11]:
output = np.dot(weight,input)
output

array([0.83327311, 0.89597071, 0.90510441, 0.80180299])

In [12]:
relu = np.maximum(0, output)

In [13]:
relu

array([0.83327311, 0.89597071, 0.90510441, 0.80180299])

In [14]:
output

array([0.83327311, 0.89597071, 0.90510441, 0.80180299])

# **Answer 2**

In [15]:
import numpy as np

# Step 1: Define Inputs
inputs = np.array([0.2, 0.4, 0.6, 0.8])

# Step 2: Initialize Random Weights and Biases
np.random.seed(42)  # Ensures reproducibility
weights = np.random.randn(4, 4)  # 4 neurons, each with 4 input weights
biases = np.random.randn(4)  # 1 bias per neuron

# Print Weights and Biases
print("Random Weights:\n", weights)
print("\nRandom Biases:\n", biases)

# Step 3: Compute Layer Output (Before Activation)
layer_output = np.dot(inputs, weights.T) + biases

# Step 4: Define ReLU Activation Function
def relu(x):
    return np.maximum(0, x)  # Replaces negative values with 0

# Step 5: Apply ReLU Activation
activated_output = relu(layer_output)

# Step 6: Print Results
print("\nLayer output (before activation):\n", layer_output)
print("\nLayer output (after ReLU activation):\n", activated_output)


Random Weights:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]]

Random Biases:
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]

Layer output (before activation):
 [ 0.638243    1.73523735 -1.43552935 -3.61400407]

Layer output (after ReLU activation):
 [0.638243   1.73523735 0.         0.        ]
