In [3]:
import torch
torch.__version__

'2.5.1+cu124'



# 1.   Tensors and Dimensions



In [2]:
# Scalars (0D)
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [4]:
# Check the number of dimensions of scalar
scalar.ndim

0

In [6]:
# Vector (1D)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

In [8]:
# Check the number of dimensions of vector
vector.ndim

1

In [9]:
# Matrix (2D)
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Check shape of matrix
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Check number of dimensions of matrix
MATRIX.ndim

2

In [12]:
# Tensor (3D)
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3


# 2.   Generating Random Tensors



In [18]:
# Creates a random tensor of shape [size (3, 4)]
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2989, 0.3505, 0.3981, 0.8590],
         [0.1879, 0.1064, 0.1103, 0.9640],
         [0.2257, 0.4008, 0.4606, 0.2172]]),
 torch.float32)

In [21]:
# Create a random tensor of size (224, 224, 3)
# creates a tensor in the HWC format (Height, Width, Channels)
# C = Number of color channels (3 for RGB)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)



# 3.   Extra function of tensor




In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [24]:
# Create a range of values 0 to 10 use arrange
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32
)

float_32_tensor.shape, float_32_tensor.dtype,

(torch.Size([3]), torch.float32)

In [27]:
# Datatype for tensors is float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print()
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.1538, 0.2402, 0.5458, 0.3405],
        [0.8625, 0.7148, 0.1472, 0.8038],
        [0.8796, 0.1279, 0.6407, 0.3760]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu




# 4.   Operation over tensor




In [32]:
# Create a tensor of values
tensor = torch.tensor([1, 2, 3])
# Add a number 10 to it
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [43]:
# Subtract 10 and reassign (stored)
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [44]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [47]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [48]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [49]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# Shapes need to be in the right way to multiply 3x2 * 2x3
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [56]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
Index where max value occurs: 9
Index where min value occurs: 0


In [64]:
# Dimension from 1 to 7
y = torch.arange(1., 8.)
print(y, y.shape)
# Add an extra dimension
x_reshaped = y.reshape(1, 7)
print(x_reshaped, x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])
tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])


In [8]:
# Stacking tensors along different dimensions
x = torch.arange(0, 100, 10)
x_stacked = torch.stack([x, x, x, x], dim=0)  # Try changing dim to 1
print("Stacked Tensor:\n", x_stacked)

Stacked Tensor:
 tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])


In [9]:
# Stacking tensors along different dimensions
x = torch.arange(0, 100, 10)
x_stacked = torch.stack([x, x, x, x], dim=1)
print("Stacked Tensor:\n", x_stacked)

Stacked Tensor:
 tensor([[ 0,  0,  0,  0],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])


In [11]:
x_reshaped = x.reshape(1, 10)  # Adds extra dimension
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
New shape: torch.Size([10])


In [12]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [15]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}\n")
print(f"Second square bracket: {x[0][0]}\n")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Second square bracket: tensor([1, 2, 3])

Third square bracket: 1




# 5.   Tensor and Numpy




In [18]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 8.0)
print(array)
print(type(array))
tensor = torch.from_numpy(array)
print(array, tensor)


[1. 2. 3. 4. 5. 6. 7.]
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [19]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5711, 0.4901, 0.5263, 0.9517],
        [0.1510, 0.3929, 0.8981, 0.4737],
        [0.3975, 0.8838, 0.5932, 0.4333]])

Tensor B:
tensor([[0.8497, 0.4261, 0.2314, 0.7962],
        [0.8383, 0.2905, 0.8959, 0.7141],
        [0.6472, 0.9569, 0.1730, 0.1642]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])



# 6.   Random seed in torch




In [21]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])